/*
 * actions.c, generated by RTE VuGen on Sun Sep 03 16:34:32 2017
 */

/*
	PowerTerm for HP Performance Software for Windows 2000/XP/2003/Vista
	Version: 9.1.0
	Copyright (C) 1994-2007 ERICOM Software Ltd.
*/

Action2()
{

	return 0;
} /* Action2() */


/* END OF FILE actions.c */
