/*
 * init.c, generated by RTE VuGen on Tue Mar 28 10:33:44 2017
 */

/*
	PowerTerm for HP Performance Software for Windows 2000/XP/2003/Vista
	Version: 9.1.0
	Copyright (C) 1994-2007 ERICOM Software Ltd.
*/


#include <lrrte.h>

vuser_init()
{
	/* *** The terminal type is VT 420-8. */
	TE_connect(
		"comm-type = telnet;"
		"host-name = 172.29.165.94;"
		"terminal-id = ;"
		"set-window-size = true;"
		"security-type = unsecured;"
		"terminal-type = vt420-8;"
		"terminal-model = vt420;"
		"login-command-file = ;"
		"terminal-setup-file = ;"
		, 60000);
	if (TE_errno != TE_SUCCESS) 
		return -1;
	TE_wait_text("login: ", 90);
	TE_wait_cursor(8, 3, 100, 90);
	TE_type("rf");
	TE_wait_text("f", 90);
	TE_wait_cursor(10, 3, 100, 90);
	TE_type("<kReturn>");
	TE_wait_text("Password: ", 90);
	TE_wait_cursor(11, 4, 100, 90);
	lr_think_time(3);
	TE_type("Yum1234!<kReturn>");

	return 0;
} /* vuser_init() */


/* END OF FILE init.c */
